FROM postgres:9.6.2-alpine
MAINTAINER johngilliland@me.com

ENV POSTGRES_PASSWORD=docker

VOLUME ~/docker/volumes/postgres:/var/lib/postgresql/data

EXPOSE 5432

CMD ["postgres"]


# docker run --rm -it -p 5432:5432 postgres-temp /bin/ash
